### ISSUE TITLE
information request

### ISSUE THREAD

**Issue by erikdubois** [addy-dclxvi/openbox-theme-collections#1]
Hi Adhi,

long time not spoken. One of my ArcoLinux users pointed me to your github for great Openbox themes.

I was thinking of creating an AUR package of this github. 

Can you confirm you will be keeping this online please?

Maybe even update it from time to time ;-)

All Arch Linux based computers can then easily install these themes.

Erik Dubois from ArcoLinux

**Comment by addy-dclxvi** [comment]
Hello Mr Dubois!

Of course I will keep it online. Even though these days my real life
business prevents me to keep online, I have no intention to take it down.
And some day I will create more contents.

Kind regards,
Addy

**Comment by erikdubois** [comment]
thanks Adhi
naming your package
openbox-themes-pambudi-git

Is that ok with you?

**Comment by addy-dclxvi** [comment]
Sure, it looks okay. But better to use my nickname (Addy) instead of my
surname.

**Comment by erikdubois** [comment]
That is too late.
In the meantime it is online already.
Thanks for your understanding and support.

**Comment by addy-dclxvi** [comment]
Okay, no worries 👍
