### ISSUE TITLE
How to change alt-tab list look.

### ISSUE THREAD

**Issue by m-kru** [addy-dclxvi/openbox-theme-collections#4]
I would like to change the look of alt-tab list. Do you know what file, and what values I need to edit?

![image](https://user-images.githubusercontent.com/26227737/84881354-042b1b80-b08e-11ea-9504-8eaa24f80362.png)

**Comment by addy-dclxvi** [comment]
It's in themerc, OSD part.. iirc

**Comment by m-kru** [comment]
You are right, thanks.
